config/routes.rb
Rails.application.routes.draw do

  resources :users, only: [:new, :create, :show]
  resources :session, only: [:new, :create, :destroy]
  resources :bands do
    resources :albums, only: [:new] do
    end
  end

  resources :albums, except: [:index, :new] do
    resources :tracks, only: [:new]
  end

  resources :tracks, except: [:index, :new]
end

app/models/album.rb
class Album < ActiveRecord::Base
  
  validates :name, :band_id, :album_type, presence: true

  belongs_to(
    :band,
    class_name: 'Band',
    foreign_key: :band_id,
    primary_key: :id
  )

  has_many(
    :tracks,
    class_name: 'Track',
    foreign_key: :album_id,
    primary_key: :id,
    dependent: :destroy
  )
end

app/models/band.rb
class Band < ActiveRecord::Base

  validates :name, presence: true
  
  has_many(
    :albums,
    class_name: 'Album',
    foreign_key: :band_id,
    primary_key: :id,
    dependent: :destroy
  )

  has_many(
    :tracks,
    through: :albums,
    source: :tracks
  )
end

app/models/track.rb
class Track < ActiveRecord::Base

  belongs_to(
    :album,
    class_name: "Album",
    foreign_key: :ablum_id,
    primary_key: :id
  )
end

app/models/user.rb
class User < ActiveRecord::Base

  validates :email, :password_digest, :session_token, presence: true
  # before_action :ensure_session_token
  validates :password, length: { minimum: 4 }
  after_initialize :ensure_session_token

  attr_reader :password

  def self.generate_session_token
    token = SecureRandom.urlsafe_base64
  end

  def self.find_by_credentials(email, password)
    user = User.find_by(email: email)
    return nil unless user
    return user if user.is_password?(password)
  end

  def reset_session_token!
    self.session_token = User.generate_session_token
    self.save!
  end

  def ensure_session_token
    self.session_token ||= User.generate_session_token
  end

  def password=(new_password)
    @password = new_password
    self.password_digest = BCrypt::Password.create(new_password)
  end

  def password
    @password ||= BCrypt::Password.new(self.password_digest)
  end

  def is_password?(pass)
    self.password.is_password?(pass)
  end

end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController

  def new
    @album = Album.new(band_id: params[:band_id])
    render :new
  end

  def edit
    @album = Album.find(params[:id])
    render :edit
  end

  def create
    @album = Album.new(album_params)
    if @album.save
      redirect_to band_url
    else
      flash.now[:errors] = @album.errors.full_messages
      render :new
    end
  end

  def show
    render :show
  end

  def destroy
  end

  private
    def album_params
      params
      .require(:album)
      .permit(:name, :band_id, :album_type)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?, :logout
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def login!(user)
    user.reset_session_token!
    session[:session_token] = user.session_token
  end

  def logout
    current_user.reset_session_token!
    session[:session_token] = nil
  end

  def current_user
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def logged_in?
    !!current_user
  end
end

app/controllers/bands_controller.rb
class BandsController < ApplicationController

  def new
    @band = Band.new
    render :new
  end

  def create
    @band = Band.new(band_params)
    if @band.save
      redirect_to band_url(@band)
    else
      flash.now[:errors] = @band.errors.full_messages
      render :new
    end
  end

  def edit
    @band = Band.find(params[:id])
    render :edit
  end

  def show
    @band = Band.find(params[:id])
    render :show
  end

  def destroy
    band = Band.find(params[:id])
    Band.delete(params[:id])
    flash[:errors] = ["#{band.name} has been deleted"]
    redirect_to new_band_url
  end

  private
    def band_params
      params.require(:band).permit(:name)
    end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController

  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.find_by(email: params[:user][:email])
    if @user && @user.is_password?(params[:user][:password])
      login!(@user)
      redirect_to user_url(current_user)
    else
      flash.now[:errors] = ["Incorrect email / password combination"]
      render :new
    end
  end

  def destroy
    logout
    redirect_to new_session_url
  end

end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController

  def new
    fail
    @track = Track.new
    render :new
  end

  def edit

  end

  def show
  end

  def destroy
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      login!(@user)
      redirect_to user_url(@user)
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def show
    render :show
  end

  private
    def user_params
      params.require(:user).permit(:email, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def auth_token
    <<-HTML.html_safe
      <input  type="hidden"
              name="authenticity_token"
              value="#{form_authenticity_token}">
    HTML
  end
end

app/views/albums/new.html.erb
<h1>Create a Album!</h1>

<%= render "shared/errors" %>

<form action="<%= albums_url %>" method="post">
<%= auth_token %>
<label for="album_name">Album name</label>
<input  type="text"
        name="album[name]"
        id="album_name"
        value="<%= @album.name %>">

<br><br>

<label for="band_name">Band</label>

<select name="album[band_id]">

  <% Band.all.each do |band| %>
    <% if @album.band_id == band.id %>
      <option value="<%= band.name %>" selected><%= band.name %></option>
    <% else %>
      <option value="<%= band.name %>"><%= band.name %></option>
    <% end %>
  <% end %>
</select>


<label for="album_type">Type</label>
<input  type="radio"
        name="album[album_type]"
        id="album_type">Live Album
<input  type="radio"
        name="album[album_type]"
        id="album_type">Studio Album

<br><br>
<input type="submit" value="Create this album!">
</form>

app/views/bands/edit.html.erb
<h1>Update Band</h1>

<%= render "shared/errors" %>

<form action="<%= bands_url %>" method="Post">
  <%= auth_token %>
  <label for="band_name">Band Name</label>
  <input  type="text"
          name="band[name]"
          id="band_name"
          value="<%= @band.name %>">
<br>
<input type="submit" value="Update the Band name">
</form>

app/views/bands/new.html.erb
<h1>Create a Band</h1>

<%= render "shared/errors" %>

<form action="<%= bands_url %>" method="Post">
  <%= auth_token %>

  <label for="band_name">Band Name</label>
  <input  type="text"
          name="band[name]"
          id="band_name"
          value="<%= @band.name %>">

  <br>
  <input type="submit" value="Create Band!">
</form>

app/views/bands/show.html.erb
<h1>Band Profile<h2>

<form>
  <%= @band.name %>
  <br>
  <%= button_to "Edit", edit_band_url, method: :get %>
  <%= button_to "Delete", band_url, method: :delete %>
  <%= button_to "Create Album", new_band_album_url(params[:id]), method: :get %>

  <% @band.albums.each do |album| %>
    <%= link_to "#{album.name}" %>
  <% end %>

</form>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MusicApp</title>
  <!-- <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %> -->
</head>
<body>

<% if logged_in? %>
  <%= current_user.email %><br>
  <%= button_to "Logout", session_url, method: :delete %>
<% end %>

<%= yield %>

</body>
</html>

app/views/session/new.html.erb
<h1>Log In</h1>

<%= render "shared/errors" %>

<form action="/session" method="Post">
  <%= auth_token %>

  <label for="user_email">Email</label>
  <input  type="text"
          name="user[email]"
          id="user_email">

  <label for="user_password">Password</label>
  <input  type="password"
          name="user[password]"
          id="user_password">

  <button>Log In</button>
</form>

app/views/shared/_errors.html.erb
<% if flash[:errors] %>
  <% flash[:errors].each do |error| %>
    <li><%= error %></li><br>
  <% end %>
<% end %>

app/views/tracks/new.html.erb
<h1>Add a new track!</h1>

<%= render "shared/errors" %>

<form action="<%= new_track %>" method="Post">
  <%= auth_token %>

  <label for="track_name">Track Name</label>
  <input  type="text"
          name="tracks[name]"
          id="track_name"
          value="<%= @track.name %>">

</form>

app/views/users/new.html.erb
<h1>Sign Up!</h1>

<%= render "shared/errors" %>

<form action="/users" method="Post">
  <%= auth_token %>

  <label for="user_email">Email</label>
  <input  type="text"
          name="user[email]"
          id="user_name"
          value="<%= @user.email %>">

  <label for"user_password">Password</label>
  <input  type="password"
          name="user[password]"
          id="user_password">

  <br>

  <input type="submit" value="Create Account!">
</form>

app/views/users/show.html.erb
<h1>HELLO</h1>

EMAIL: <%= current_user.email %>